### ISSUE TITLE
Hook up email signup form

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-desktop#33]
Blocks #30

**Comment by adamlofting** [comment]
This page is an example of a form that posts to a BSD mailing list. 
https://welcome.webmaker.org/pledge/teach-the-web/

I don't know if there is any official documentation around, but it appears to interact with a 'hidden' BSD form hosted here:
https://sendto.mozilla.org/page/s/pledge-to-teach

The repo for the welcome.w.o front end pages is here:
https://github.com/mozilla/webmaker-landing-pages/

If that is helpful, and you want to use the same process for this landing page, I can setup another BSD 'hidden' form so that the email signups get saved into an identifiable list.
