### ISSUE TITLE
Fix button style in IE 10

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-desktop#41]
Blocks #30 

The button label "GO" is too high vertically on Internet Explorer 10. It is currently rendering properly in Firefox and Chrome latest.

![](https://k88hudson-screenshots.s3.amazonaws.com/screen-shots/k88mac@2x_2015-05-07_at_11.33.36_PM.png)

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by sanjaygouri** [comment]
Hello Andrew,

As am working on this issue i started testing this ,unfortunately i found another issue where  The display was not correct and it is working very well in chrome and Firefox. The only  problem is  with IE10.

![untitled1](https://cloud.githubusercontent.com/assets/7525072/7614728/55086c22-f9b6-11e4-83ae-e0b0f1fe18a0.png)

So i started working on this i solved this by adding just 2 lines in main.css so here is the result. Now it is working very well in all browsers .  

![exact](https://cloud.githubusercontent.com/assets/7525072/7614770/98139370-f9b6-11e4-8225-acf765a42d7f.png)

I hope what i did is correct so shall i create Pull Request for this so that you can update it .
Coming to the actual issue i will  update to you as soon as possible 

Cheers
Sanjay

**Comment by thisandagain** [comment]
Thanks @sanjaygouri ! Yes, please send along a PR and we'll review / land today. :+1: :smile:

**Comment by sanjaygouri** [comment]
Hello andrew am back again well this time with the actual bug this is how it is getting displayed by using line-height property in IE10.
![ie issue solved](https://cloud.githubusercontent.com/assets/7525072/7669989/f31d037e-fcad-11e4-989f-22cfaff0fb66.png)

As we have to check other browsers  also so this is how it getting displayed in chrome and firefox
1. FIREFOX 
   ![firefox no issue](https://cloud.githubusercontent.com/assets/7525072/7670004/40c1b3ae-fcae-11e4-9f47-d3b8bb633f18.png)

2.CHROME
![chrome no issue](https://cloud.githubusercontent.com/assets/7525072/7670005/4da8222e-fcae-11e4-9487-c0dc67550195.png)

waiting for your response .

**Comment by thisandagain** [comment]
Looks great! Please send along a PR and we will take a look. Thanks for your help!

**Comment by thisandagain** [comment]
Resolved in #63
