### ISSUE TITLE
Design space for partner promotion on landing page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#68]
Webmaker.org currently includes a shout-out to teach dot moz on the homepage. We will want to translate this to the new beta landing page. This space will be used initially by Maker Party when we relaunch.

Step one: figure out how promotions can fit nicely on the page. Specifics for Maker Party will be handled separately.

**Comment by xmatthewx** [comment]
I see two options for integrating external promotions without big disrupting to the current CTA 
1. @vazquez included a secondary CTA in the footer. We could allocate a certain percentage of views to teach, maker party, and webmaker. Cycle continuous tests for each. (Button style should be improved.)
2. For announcements closely coupled with Webmaker, we can utilize a text link across the top of the page. These destinations should include a download link for the app. (Color needs to be changed to dial back the prominence in this first draft.)

![landing-promo-space](https://cloud.githubusercontent.com/assets/53411/7870668/dbc627ba-0558-11e5-8a90-ec0168624a74.png)

**Comment by xmatthewx** [comment]
Maker Party has a lot more color that will likely clash with the gradient and phone. @vazquez - we'll need to think of a few ways to handle that. Wondering if we can get by with a single-color maker party logo. Maybe go full color on :hover.

**Comment by vazquez** [comment]
Here is how cross-promotion could look like on webmaker.org.
- Create a full width banner
- Include Headline, Subheadline, and a clear CTA
- Utilize a subtle background colour on the banner that meshes with the Webmaker brand. 
  - This is so that the promo space doesn't interfere with Webmaker's primary CTA.
- A background pattern would be encouraged to make promo space unique.
- If logos are required, they should be flat white to adhere to the Webmaker visual language.

#### Design

##### Promo Version A

![app landing page promo a](https://cloud.githubusercontent.com/assets/1119821/7962517/c45b1a90-09db-11e5-931b-3d6ef198964e.png)  

---

##### Promo Version B

![app landing page promo b](https://cloud.githubusercontent.com/assets/1119821/7962522/c9e2b9dc-09db-11e5-8973-6e0581cbeb9f.png)

**Comment by xmatthewx** [comment]
Fab. If we have a :+1: from @thisandagain as well, I will take this design and the guidelines to the teach team.

**Comment by thisandagain** [comment]
Nice. Do we want to spec colors for the background options to keep it in the visual system ala `mozilla.org`?

**Comment by vazquez** [comment]
Once I'm done Google Play Store assets I can definitely create a palette. :+1:

**Comment by HPaulJohnson** [comment]
Talked to @amirad briefly about Maker Party in this space. I think we can be flexible on colors so that it fits with the Webmaker design. 

Given Maker Party is right around the corner, I suggest we design this initial iteration for Maker Party, rather than the current "start teaching" CTA as we are ready to start promoting MP now.

**Comment by vazquez** [comment]
@HPaulJohnson Cool, I can do that. Could I get copy for headline, subheadline, and CTA?

**Comment by xmatthewx** [comment]
Done! Promo space designed. Color and guidelines will continue in #79. Maker Party promo will continue in https://github.com/mozilla/teach.webmaker.org/issues/737
