### ISSUE TITLE
Add OG tags to projects in player

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#82]
Add open graph meta tags for better project sharing. Include thumbnails.

**Comment by secretrobotron** [comment]
### On Facebook
- Can we show the same thumbnail that appears in the gallery?
- "Check out what I created on Mozilla Webmaker: <Project Title>"
- Description of Webmaker

**Comment by secretrobotron** [comment]
Idea: https://docs.google.com/presentation/d/1fdb6gJ1XMY7UJdh9Ac5r8_Ic0PAnimEKVXkj9w7wD6w/edit#slide=id.gb30f58fab_1_20

**Comment by KevZawacki** [comment]
Summoning @HPaulJohnson, who can help.

We could write the tags to drive home Webmaker's mission. Something like: "Mozilla Webmaker allows you to read, write and participate on the Web." Or, write something more colloquial: "With Mozilla Webmaker, create something cool and share it with friends." 

I vote the latter, since this language will live on social media.

Re: the thumbnail. I like the idea of showing a cool make. We probably don't want it to be of the specific make being shared (don't even know if that's an option).

**Comment by secretrobotron** [comment]
> We probably don't want it to be of the specific make being shared

Why not? Better brand representation if we just show the logo?

**Comment by xmatthewx** [comment]
Since this is for sharing projects and not the app, I think the content should be project specific. Unless I'm misunderstanding.

We should show the project's thumbnail and the text should be: [project title] by [username]. We could add: Made with Webmaker[link]...  Or we could stay out of the way and just let the player do the work with its CTA.

**Comment by xmatthewx** [comment]
tracking here: https://github.com/mozilla/webmaker-core/issues/453

**Comment by Pomax** [comment]
it would seem the most sensible to use the make's thumbnail, since that's what twitter, facebook, etc. will show. "sharing your work" but then only getting the Webmaker logo feels a bit like forced advertisement, rather than discovery that entices people to also grab the webmaker app =)
